### PR TITLE
Add shellcheck as an on-save handler for shell scripts.

### PR DESCRIPTION
**Pull request by schinckel**
Marks the current file with warning/error/notes as applicable.

Includes documentation and binary.

### CODE REVIEW

**Comment by schinckel** [comment]
I've erred on the side of caution, and included the shellcheck binary, and all of the files that were installed by `brew install shellcheck`

**Comment by schinckel** [comment]
Oh, http://www.shellcheck.net/about.html

**Comment by schinckel** [comment]
Yeah, a standalone bundle could be best. 

One other alternative is to use an environment variable for the command location (it's brew-installable). However, having a single install process would be simpler.

**Comment by mkhl** [comment]
> One other alternative is to use an environment variable for the command location (it's brew-installable).

Right, that way we could leave this command in the bundle and leave installation to the user.
The C bundle provides a nice example for this (see the `requiredCommands` key in `~/Library/Application\ Support/TextMate/Managed/Bundles/C.tmbundle/Commands/Reformat\ Document.tmCommand`).

When doing that though I’d prefer this to be a “Validate Style” kind of command (the common shortcut for those is ⌃⇧V) so users don’t have to install GHC just to save shell scripts.

Which way do you prefer?

**Comment by sorbits** [comment]
Using the `requiredCommands` (without putting the binary in the bundle) and putting it on <kbd>⌃⇧V</kbd> sounds like the best way.

You can include instructions about how to set it up to run on save.

And as for `requiredCommands` this can be set to look in common install locations (like homebrew’s), so all the user need to do is run `brew install shellcheck`.

**Comment by MikeMcQuaid** [comment]
@schinckel This feels like something that https://github.com/sxtxixtxcxh/validate-on-save.tmbundle may be interested in?

**Comment by mkhl** [comment]
This change seems to have found its way into https://github.com/sxtxixtxcxh/validate-on-save.tmbundle. Feel free to reopen if you want to discuss this further.

**Pull request closed without merging**
